wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
epochs:
  desc: null
  value: 15
optimizer:
  desc: null
  value: SDG
momentum:
  desc: null
  value: 0.9
_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.15.9
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1703757116.958838
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 76
      - 105
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 76
      - 105
      3:
      - 2
      - 15
      - 16
      - 23
      4: 3.10.10
      5: 0.15.9
      8:
      - 1
      - 2
      - 4
      - 5
