name: learn-github-actions

on: [push]
jobs:
  first-job-on-github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: hello
        run: |
          echo "hello, bonjour" 
      - name: run python script
        run: |
          pip install -r requirements.txt
          python ci/py
